=begin
#Omnichannel API

#Messente's API which allows sending messages via various channels with fallback options.

OpenAPI spec version: 0.0.2
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::OmnimessageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OmnimessageApi' do
  before do
    # run before each test
    @instance = OpenapiClient::OmnimessageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OmnimessageApi' do
    it 'should create an instance of OmnimessageApi' do
      expect(@instance).to be_instance_of(OpenapiClient::OmnimessageApi)
    end
  end

  # unit tests for cancel_scheduled_message
  # Cancels a scheduled Omnimessage
  # @param omnimessage_id UUID of the scheduled Omnimessage to be cancelled
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_scheduled_message test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send_omnimessage
  # Sends an Omnimessage
  # @param omnimessage Omnimessage to be sent
  # @param [Hash] opts the optional parameters
  # @return [OmniMessageCreateSuccessResponse]
  describe 'send_omnimessage test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
