=begin
#Omnichannel API

#Messente's API which allows sending messages via various channels with fallback options.

OpenAPI spec version: 0.0.2
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/channel'
require 'openapi_client/models/delivery_report_response'
require 'openapi_client/models/delivery_result'
require 'openapi_client/models/err'
require 'openapi_client/models/error_item'
require 'openapi_client/models/error_response'
require 'openapi_client/models/message'
require 'openapi_client/models/message_result'
require 'openapi_client/models/omni_message_create_success_response'
require 'openapi_client/models/omnimessage'
require 'openapi_client/models/response_error_code'
require 'openapi_client/models/response_error_title'
require 'openapi_client/models/sms'
require 'openapi_client/models/status'
require 'openapi_client/models/viber'
require 'openapi_client/models/whats_app'
require 'openapi_client/models/whats_app_audio'
require 'openapi_client/models/whats_app_document'
require 'openapi_client/models/whats_app_image'
require 'openapi_client/models/whats_app_text'

# APIs
require 'openapi_client/api/delivery_report_api'
require 'openapi_client/api/omnimessage_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
