=begin
#Omnichannel API

#Messente's API which allows sending messages via various channels with fallback options.

OpenAPI spec version: 0.0.2
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

require 'date'

module Omnichannel
  class ResponseErrorCode
    
    N101 = '101'.freeze
    N102 = '102'.freeze
    N103 = '103'.freeze
    N104 = '104'.freeze
    N105 = '105'.freeze
    N106 = '106'.freeze
    N107 = '107'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ResponseErrorCode.constants.select { |c| ResponseErrorCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ResponseErrorCode" if constantValues.empty?
      value
    end
  end

end
